apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    syncRepo: https://github.com/erpost/anthos.git
    syncBranch: master
    secretType: none
    policyDir: "config-root"
